# Default configuration for goTOV.
# This file is copied to config.yaml inside the Docker image.
# All values can be overridden by environment variables.
# For example, `opcua.endpoint` can be set by the env var `GOTOV_OPCUA_ENDPOINT`.

opcua:
  endpoint: "opc.tcp://<ip_or_hostname>:4840"
  username: ""
  password: ""

logging:
  level: "info" # "debug" is also a good option

server:
  listen_addr: ":8085"

fermentation:
  enabled: true
  database_path: "data/fermentation.db" # Path inside the container

  hysteresis:
    cooling: 0.3
    heating: 0.3

  step_check_interval: "30s"
  stabilization_time: "10m"

brewfather:
  user_id: "" # Your Brewfather User ID
  api_key: "" # Your Brewfather API Key